### PR TITLE
#160374936 Change the landing page background image

### PR DESCRIPTION
**Pull request by AGMETEOR**
#### What does this PR do?
This PR changes the background image to another as requested by the PO.
#### What are the relevant pivotal tracker stories?
[#160374936](https://www.pivotaltracker.com/story/show/160374936)
#### Screenshots
screen shot 2018-09-10 at 09 06 54

### CODE REVIEW

**Comment by lytes20** [comment]
Hey @AGMETEOR , nice work, could you also implement this feedback from the PO in this PR
- Make `Author's Haven` uppercase
- Make all the other subsequent titles uppercase that is Most Popular and Recent stories

**Comment by AGMETEOR** [comment]
@lytes20 let me implement those changes.

**Comment by AGMETEOR** [comment]
@lytes20 changes have been made.

**Comment by lytes20** [comment]
Seen the changes, one is left however on the home page
screen shot 2018-09-10 at 09 49 41

**Comment by AGMETEOR** [comment]
@lytes20 I have worked on it.

**Review by lytes20 — APPROVED** [review]

**Pull request merged**
