### PR TITLE
#160228797 Users view all articles

### PR DESCRIPTION
**Pull request by lytes20**
#### What does this PR do?
- Enable users to view all articles
#### Description of Task to be completed?
- This PR displays all articles on the page using a Mansory grid
#### How should this be manually tested?
- By running the app, visiting the home page, looking at recent articles and then also viewing all articles
#### Any background context you want to provide?
- For users to view available articles in a nice manner
#### What are the relevant pivotal tracker stories?
[#160228797 ](https://www.pivotaltracker.com/story/show/160228797)
#### Screenshots
Preview
screen shot 2018-09-19 at 18 04 19

Tests and coverage
screen shot 2018-09-19 at 17 43 06

### CODE REVIEW

**Review by phillipseryazi — APPROVED** [review]

**Review by ssewilliam — APPROVED** [review]

**Comment by AGMETEOR** [comment]
@lytes20 can most popular also be dynamic like recent articles?

**Comment by abulojoshua1** [comment]
@AGMETEOR, I agree with that, the Author name and date should be dynamic.

**Comment by lytes20** [comment]
@AGMETEOR  unfortunately right now, it cant, this because we need to implement logic for read count and then return a list of most read articles, and this logic would be best placed in the backend, but as you can see we already have a backlog to clear for frontend by tomorrow. So the popular article thing will just be there as a dummy.

**Comment by geofrocker** [comment]
@lytes20 @AGMETEOR Can this be done using the `favoritesCount` property of an article?

**Comment by lytes20** [comment]
@geofrocker I guess, it can be done like that, but I feel like that logic would be best implemented in the backend where we have an endpoint that returns the top three articles with the highest number of favorites.

**Review by RutaleIvanPaul — APPROVED** [review]

**Pull request merged**
