### PR TITLE
#160292200 Add props destructuring to props

### PR DESCRIPTION
**Pull request by AGMETEOR**
#### What does this PR do?
This PR adds props destructuring and the use of HTML entities to escape quotes. 
#### Background context
Props destructuring is a JavaScript best practice. Example of destructured props,
const { show } = this.props;
HTML entities are used to display reserved characters like quotes('), greater than sign (>) that could potentially get mixed up by the browser. Use &lt; or &#60; instead of (>) in text to rendered by the browser.
#### What are the relevant pivotal tracker stories?
[#160292200](https://www.pivotaltracker.com/story/show/160292200)

### CODE REVIEW

**Review by lytes20 — APPROVED** [review]

**Review by abulojoshua1 — APPROVED** [review]

**Comment by geofrocker** [comment]
Have folders for actions, components and reducers in the tests folder

**Comment by geofrocker** [comment]
Work on the vulnerability warning for jquery

**Comment by AGMETEOR** [comment]
@geofrocker which warning? I have no jquery warnings.

**Comment by geofrocker** [comment]
Follow this [link](https://github.com/andela/ah-frontend-taces/network/dependencies)

**Review by phillipseryazi — APPROVED** [review]

**Comment by AGMETEOR** [comment]
@geofrocker I have worked on the changes.

**Pull request merged**
