### PR TITLE
[Chore #159951815] Setup SASS processing

### PR DESCRIPTION
**Pull request by lytes20**
#### What does this PR do?
- Setup SASS processing on the client
#### Description of Task to be completed?
- Install and setup sass pre-processing on the application to enables the use of both .scss and .css files on the client
#### How should this be manually tested?
- By creating a `.scss`  file and using it
#### Any background context you want to provide?
- Sass is css with superpowers, it allows you to write more powerful css
#### What are the relevant pivotal tracker stories?
[#159951815](https://www.pivotaltracker.com/story/show/159951815)
#### Screenshots
screen shot 2018-08-28 at 12 33 20

screen shot 2018-08-28 at 12 33 34

#### Questions:

### CODE REVIEW

**Review by abulojoshua1 — APPROVED** [review]

**Review by phillipseryazi — APPROVED** [review]

**Review by AGMETEOR — APPROVED** [review]

**Review by ssewilliam — COMMENTED** [review]
@lytes20 
Were all these changes that you have made to the files in your PR necessary?

**Comment by lytes20** [comment]
@ssewilliam the may changes you referring to  are because of the code format we are following, the double quotes instead of the single quotes

**Comment by lytes20** [comment]
@ssewilliam does the above comment answer you?

**Comment by ssewilliam** [comment]
@lytes20 
Great initiative

**Review by ssewilliam — APPROVED** [review]

**Review by RutaleIvanPaul — APPROVED** [review]

**Pull request merged**
